[project]
name = "autotest"
version = "0.2.0"
description = "UI Autotests (Selenium + PyTest + Allure)"
requires-python = ">=3.10"
dependencies = [
    "allure-pytest>=2.15.3",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "pytest>=9.0.2",
    "selenium>=4.40.0",
]
